server:
  port: 8080

spring:
<<<<<<< HEAD
  main:
    allow-circular-references: true
=======
>>>>>>> 3ce69a9... HW08-MONGO init commit without test
  data:
    mongodb:
      database: library

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw08mongo.changelog
