quizapplication:
  locale: "en-US"
  passingscore: 3
  filepath: /questions/questions_%s.csv
  numberOfQuestion: 5
spring:
  banner:
    location: banner/banner.txt
  messages:
    basename: i18n/messages
