logging:
  level:
    root: error
    org.springframework: error
server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
